[package]
name = "gce-hoster"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
regex = "1.11.1"
walkdir = "2"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"